service: nestjs-serverless-pg

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  architecture: arm64
  stage: 'dev'
  region: 'us-east-1'
  memorySize: 128
  logRetentionInDays: 1
  timeout: 15

functions:
  api:
    handler: dist/main.handler
    events:
      - httpApi:
          method: any
          path: '{proxy+}'

plugins:
  - serverless-jetpack
  - serverless-offline